# Generated by Django 3.2.5 on 2021-07-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homework_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('submitted', 'Submitted'), ('canceled', 'Canceled')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
