# Generated by Django 3.2.5 on 2021-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210706_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Submitted', 'Submitted'), ('Canceled', 'Canceled')], default='Submitted', max_length=10),
        ),
    ]
