# Generated by Django 3.2.5 on 2021-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='image',
            field=models.ImageField(default='', upload_to='homeworks'),
            preserve_default=False,
        ),
    ]
