# Generated by Django 3.2.5 on 2021-07-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_id_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='upload',
            field=models.FileField(default=' ', upload_to='homeworks/'),
            preserve_default=False,
        ),
    ]
