# Generated by Django 3.2.5 on 2021-07-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_homework_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='image',
        ),
    ]
