# Generated by Django 3.2.5 on 2021-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210725_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Completed', 'Checked'), ('Canceled', 'Canceled')], default='Submitted', max_length=10),
        ),
    ]
