# Generated by Django 3.2.5 on 2021-07-26 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
    ]
