# Generated by Django 3.2.5 on 2021-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_homework_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Checked', 'Checked'), ('Canceled', 'Canceled')], default='Submitted', max_length=10),
        ),
    ]
